#!/usr/bin/env python3
# Copyright (C) 2018- DEEPX Ltd. All rights reserved.
"""Regenerate config/test_models.conf from config/model_registry.json.

Column 1 is the FAMILY -- the python example directory and the C++ executable
basename under the dx-modelzoo layout -- and column 4 the variant. The registry is the
single source of truth, so this file is generated rather than hand-maintained; it
drifted to 347 rows against 353 entries before.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HEADER = """# DX-APP Model Test Registry (auto-generated by scripts/regen_test_models_conf.py)
# ==============================================================================
# Format: family<TAB>task<TAB>model_file<TAB>variant
#
# Under the dx-modelzoo family/variant layout one example serves every variant of
# its family, so column 1 is the FAMILY -- which is also the python directory name
# and the C++ executable basename -- and column 4 names the variant. Consumers that
# read only the first three columns keep working: the model path alone identifies
# the variant, and both the python and C++ entry points derive it from -m.
#
# Tasks are dx-modelzoo's 23. Regenerate with:
#   python3 scripts/regen_test_models_conf.py
# ==============================================================================
"""


def main() -> None:
    reg = json.loads((ROOT / "config" / "model_registry.json").read_text(encoding="utf-8"))
    rows = [
        f"{e['family']}\t{e['task']}\tassets/models/{e['dxnn_file']}\t{e['variant']}"
        for e in sorted(reg, key=lambda x: (x["task"], x["family"], x["variant"]))
    ]
    out = ROOT / "config" / "test_models.conf"
    out.write_text(HEADER + "\n".join(rows) + "\n", encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)}: {len(rows)} rows")


if __name__ == "__main__":
    main()
