name: (public-release)
run-name: ${{github.triggering_actor}} - Public Release

on:
  workflow_dispatch:
    inputs:
      target_commit:
        description: "Target commit from main to release"
        required: false
        default: 'latest'
      manual_release:
        type: boolean
        description: "Manual release"
        required: false
        default: true

permissions: write-all

jobs:
  set_commit:
    name: Set Target Commit
    runs-on:
      - self-hosted
    outputs:
      commit_sha: ${{ steps.set_commit.outputs.commit_sha }}
    steps:
      - name: Set target commit
        id: set_commit
        run: |
          if [ "${{ github.event.inputs.target_commit }}" = "latest" ]; then
            echo "Using latest commit: ${{ github.sha }}"
            echo "commit_sha=${{ github.sha }}" >> $GITHUB_OUTPUT
          else
            echo "Using specified commit: ${{ github.event.inputs.target_commit }}"
            echo "commit_sha=${{ github.event.inputs.target_commit }}" >> $GITHUB_OUTPUT
          fi

  call_public_release:
    name: Execute Public Release
    needs: set_commit
    uses: deepx/do_workflows-central/.github/workflows/public-release.yml@main
    with:
      target_commit: ${{ needs.set_commit.outputs.commit_sha }}
      manual_release: ${{ github.event.inputs.manual_release }}
      internal_repo: deepx/dx_app
      public_repo: DEEPX-AI/dx_app
    secrets:
      internal_token: ${{ secrets.GH_DCI_TOKEN }}
      public_token: ${{ secrets.GC_DCI_TOKEN }}
